language: python
python:
  - "3.8"

install:
  - "pip install --upgrade pip"
  - "pip install -r ./requirements.txt"

script:
  - "python ./main.py"

notifications:
  email:
    recipients:
      - royopa@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
